# Generated by Django 4.0 on 2022-12-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category1_slug_item_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('Item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='shop.item')),
            ],
        ),
    ]
