# Generated by Django 4.0 on 2022-12-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_itemrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
